In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Titanic-Dataset.csv")

In [2]:
df.shape

(891, 12)

In [3]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
686,687,0,3,"Panula, Mr. Jaako Arnold",male,14.0,4,1,3101295,39.6875,NaN,S

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
missing_percent =(df.isnull().sum()/len(df))*100
missing_percent.sort_values(ascending=False)

Cabin          77.104377
Age            19.865320
Embarked        0.224467
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
dtype: float64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [14]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [15]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [16]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [17]:
df[["Age","Fare"]].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [18]:
Q1 = df["Fare"].quantile(0.25)
Q3 = df["Fare"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Fare"] < lower) |
    (df["Fare"] > upper)
]

len(outliers)

116

## NumPy Statistical Analysis

In [19]:
numeric_cols = ["Age", "Fare"]

In [30]:
np.mean(df["Age"])
np.mean(df["Fare"])

np.float64(32.204207968574636)

In [32]:
np.median(df["Age"].dropna())

np.float64(28.0)

In [31]:
np.median(df["Fare"])

np.float64(14.4542)

In [39]:
np.var(df["Age"].dropna())
np.var(df["Fare"])

2466.6653116850434

In [25]:
np.std(df["Age"].dropna())
np.std(df["Fare"])

49.66553444477411

In [35]:
np.percentile(df["Age"].dropna(), [25,50,75])

array([20.125, 28.   , 38.   ])

In [36]:
np.percentile(df["Fare"], [25,50,75])

array([ 7.9104, 14.4542, 31.    ])

In [37]:
np.min(df["Age"])
np.max(df["Age"])

np.min(df["Fare"])
np.max(df["Fare"])

512.3292

## Univariate Analysis

In [40]:
numeric_cols = df.select_dtypes(include=np.number).columns

print(numeric_cols)

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [41]:
col = "Age"

print("Mean:", np.mean(df[col]))
print("Median:", np.median(df[col].dropna()))
print("Std:", np.std(df[col].dropna()))
print("Min:", np.min(df[col]))
print("Max:", np.max(df[col]))
print("Missing:", df[col].isnull().sum())

Mean: 29.69911764705882
Median: 28.0
Std: 14.516321150817317
Min: 0.42
Max: 80.0
Missing: 177

In [42]:
col = "Fare"

print("Mean:", np.mean(df[col]))
print("Median:", np.median(df[col]))
print("Std:", np.std(df[col]))
print("Min:", np.min(df[col]))
print("Max:", np.max(df[col]))

Mean: 32.204207968574636
Median: 14.4542
Std: 49.66553444477411
Min: 0.0
Max: 512.3292

In [43]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [44]:
(df["Sex"].value_counts(normalize=True)*100).round(2)

Sex
male      64.76
female    35.24
Name: proportion, dtype: float64

In [45]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [46]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [47]:
(df["Pclass"].value_counts(normalize=True)*100).round(2)

Pclass
3    55.11
1    24.24
2    20.65
Name: proportion, dtype: float64

In [48]:
pd.crosstab(df["Sex"], df["Survived"])

Survived    0    1
Sex
female     81  233
male      468  109

In [49]:
pd.crosstab(
    df["Sex"],
    df["Survived"],
    normalize="index"
) * 100

Survived          0          1
Sex
female    25.796178  74.203822
male      81.109185  18.890815

##### it means 74% female and 18% male survived due to evacuation policy

In [50]:
pd.crosstab(
    df["Pclass"],
    df["Survived"],
    normalize="index"
) * 100

Survived          0          1
Pclass
1         37.037037  62.962963
2         52.717391  47.282609
3         75.763747  24.236253

In [51]:
pd.crosstab(
    df["Embarked"],
    df["Survived"],
    normalize="index"
) * 100

Survived          0          1
Embarked
C         44.642857  55.357143
Q         61.038961  38.961039
S         66.304348  33.695652

In [52]:
df.corr(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000

In [53]:
df.corr(numeric_only=True)["Survived"]

PassengerId   -0.005007
Survived       1.000000
Pclass        -0.338481
Age           -0.077221
SibSp         -0.035322
Parch          0.081629
Fare           0.257307
Name: Survived, dtype: float64

In [54]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [55]:
df.groupby("Survived")["Age"].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

In [56]:
df.groupby("Survived")["Fare"].mean()

Survived
0    22.117887
1    48.395408
Name: Fare, dtype: float64

#### the survivor had pay more higher fees than non survivor

In [57]:
corr = df.corr(numeric_only=True)

corr["Survived"].sort_values(ascending=False)

Survived       1.000000
Fare           0.257307
Parch          0.081629
PassengerId   -0.005007
SibSp         -0.035322
Age           -0.077221
Pclass        -0.338481
Name: Survived, dtype: float64